### ISSUE TITLE
How do donors work?

### ISSUE THREAD

**Issue by WindowsNT** [zavolokas/Inpainting#44]
The donor format is, assumed, the same as the mask: Pixels that describe the donor have alpha = 1.
The result doesn't seem to use the donor. Even If I omit the donor, the result is the same.

![org](https://user-images.githubusercontent.com/4609006/134783709-7559dbc4-bc13-4bcf-96e6-e99c9c1217a8.jpg)
![mask](https://user-images.githubusercontent.com/4609006/134783708-ac388d9c-034f-4437-b6d5-703803bed0f4.png)
![donor](https://user-images.githubusercontent.com/4609006/134783712-762a8e1c-eafd-44d2-a434-24bec3622857.png)
![out](https://user-images.githubusercontent.com/4609006/134783710-6a79f03b-c3fa-404d-b138-f41f64b0e5a1.jpg)

**Comment by zavolokas** [comment]
@WindowsNT the donor mask should not only mark the area of the source for the inpainting, but it also should mark a part(or whole) inpianted area so that the algorithm will understand that you want a particular destination to be inpainted with a particular source.

In your case you can try to have the donor as concatenation of your current donor and your mask.

**Comment by WindowsNT** [comment]
Ah OK, it wasn't clear. I tested it and it works that way.
Best,
